/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CBibleEngine */

#ifndef _Included_CBibleEngine
#define _Included_CBibleEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CBibleEngine
 * Method:    StartEngine
 * Signature: (ILjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_CBibleEngine_StartEngine
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     CBibleEngine
 * Method:    ConvertStringToReference
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_CBibleEngine_ConvertStringToReference
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
