/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_southern_CBibleEngine */

#ifndef _Included_edu_southern_CBibleEngine
#define _Included_edu_southern_CBibleEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_southern_CBibleEngine
 * Method:    StartEngine
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_StartEngine
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    StopEngine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_StopEngine
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetTotalVerses
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetTotalVerses
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetTotalWords
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetTotalWords
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    ConvertStringToReference
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_ConvertStringToReference
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    ConvertStringToReferenceLen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_ConvertStringToReferenceLen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    ConvertReferenceToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_southern_CBibleEngine_ConvertReferenceToString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetReference
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_southern_CBibleEngine_GetReference
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    FindWord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_FindWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    FindFirstWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_southern_CBibleEngine_FindFirstWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    FindNextWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_southern_CBibleEngine_FindNextWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    FindPreviousWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_southern_CBibleEngine_FindPreviousWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetOccurences
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetOccurences
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetBitMapOccurences
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetBitMapOccurences
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetWordBitMap
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_southern_CBibleEngine_GetWordBitMap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetStrongsWordBitMap
 * Signature: (CJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_southern_CBibleEngine_GetStrongsWordBitMap
  (JNIEnv *, jobject, jchar, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetNextConcordanceReference
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetNextConcordanceReference
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetPreviousConcordanceReference
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetPreviousConcordanceReference
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    StartMarginEngine
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_edu_southern_CBibleEngine_StartMarginEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    StopMarginEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_southern_CBibleEngine_StopMarginEngine
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    ReStartMarginEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_southern_CBibleEngine_ReStartMarginEngine
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetTotalMarginVerses
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetTotalMarginVerses
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetFirstMargin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_GetFirstMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetNextMargin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_GetNextMargin
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetPreviousMargin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_GetPreviousMargin
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetMargin
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_edu_southern_CBibleEngine_GetMargin
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    StartLexiconEngine
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_edu_southern_CBibleEngine_StartLexiconEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    StopLexiconEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_southern_CBibleEngine_StopLexiconEngine
  (JNIEnv *, jobject);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetStrongs
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetStrongs
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetNumStrongs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_southern_CBibleEngine_GetNumStrongs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_southern_CBibleEngine
 * Method:    GetDef
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_southern_CBibleEngine_GetDef
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
